### ISSUE TITLE
./gradlew bootRun does not work. Build failure

### ISSUE THREAD

**Issue by bondar-artem** [shirohoo/realworld-java21-springboot3#4]
Hi

I was trying to follow the readme, but unfortunately, I cannot run the app.

Executing the `./gradlew bootRun` results in the error:
```
Execution failed for task ':bootRun'.
> Failed to calculate the value of task ':bootRun' property 'mainClass'.
> Main class name has not been configured and it could not be resolved from classpath
``` 

System:
MaOS Sonoma 14.2
Java 21

![image](https://github.com/shirohoo/realworld-java21-springboot3/assets/21285622/e52cc35c-a0c8-4106-a433-784383efda26)

**Comment by shirohoo** [comment]
Hello. It seems I missed updating the documentation while transitioning the project to a modular monolithic structure. 

Please try entering `./gradlew :modular-application:bootRun.`

**Comment by bondar-artem** [comment]
Thank you! :)
Could you help me with one more question, please? I am trying to run this backend with a fronted for the app, but having an integration issue when running both on the localhost.
This is a frontend: https://github.com/gothinkster/angular-realworld-example-app
Currently, it's configured to run against deployed API which is https://api.realworld.io/api

When I change the API URL in the application to http://localhost:8080/api, it does not work. The browser console shows a 200 status code, but no response body is returned to the application. I suspect it's related to CORS, but can't figure out how to fix this.

Could you provide a suggestion, please?

**Comment by shirohoo** [comment]
There was indeed a CORS problem. I changed the code and pushed a commit to the repository to resolve the issue. Thank you so much for your input. 

One thing I am concerned about is that since this project focuses only on writing good server code, I did not expect to attach the client app directly to this project. 

In particular, the server's exception handling specifications do not follow RealWorld's specifications, and I arbitrarily wrote them according to the [https://datatracker.ietf.org/doc/html/rfc7807](https://datatracker.ietf.org/doc/html/rfc7807) protocol, so the client app probably does not work as expected for exception situations.
